---
- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: yes

- name: Install Helm
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
  args:
    creates: /usr/local/bin/helm
  become: yes